window.imgData=[
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
	    src:'img11.jpg',
	    src2:'logo10.png',
	    dec2:'植美村 |【驻颜小金瓶】24K黄金烟...',
	    dec3:'24K驻颜小金瓶',
	    value:'￥58',
	},
	{
		src:'img21.jpg',
	    src2:'logo11.png',
	    dec2:'贝德玛 | 贝德玛 舒颜多效卸妆水2...',
	    dec3:'温和卸妆 彩妆无残留',
	    value:'￥138',
	},
	{
		src:'img22.jpg',
	    src2:'logo12.png',
	    dec2:'雅漾 | Avene 雅漾舒护活泉水 300ml...',
	    dec3:'明星喷雾 活泉补水',
	    value:'￥65',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
	{
		src:'img30.jpg',
	    src2:'logo13.png',
	    dec2:'珀莱雅 | 【一盒三芯】柏莱雅 光感...',
	    dec3:'1盒3芯',
	    value:'￥79',
	},
]
